FROM develop

RUN sudo apt-get update &&\
    sudo apt-get install -y gcc &&\
    sudo apt-get install -y cmake &&\
    sudo apt-get install -y clang && \
    sudo apt-get install -y gcc && \
    sudo apt-get install -y g++ && \
    sudo apt-get install -y gdb && \
    sudo apt-get install -y clang-tidy && \
    sudo apt-get install -y clang-format && \
    sudo apt-get install -y cmake-curses-gui && \
    sudo apt-get install -y llvm && \ 
    sudo apt-get install -y libboost-dev && \
    sudo apt-get install -y libboost-all-dev


