#!/usr/bin/env bash

# shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.dotfiles

# Stash your environment variables in ~/.localrc. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# all of our zsh files
#typeset -u config_files
#config_files=($ZSH/**/*.sh)
#echo $config_files

# load the path files
#for file in ${(M)config_files:#*/path.sh}
for file in $(find $ZSH/ -maxdepth 2 -name path.sh)
do
  source $file
done

# load everything but the path and completion files
#for file in ${${config_files:#*/path.sh}:#*/completion.sh}
for file in $(find $ZSH/ -maxdepth 2 -name env.sh -or -name alias.sh)
do
  source $file
done

# initialize autocomplete here, otherwise functions won't be loaded
#autoload -U compinit
#compinit

# load every completion after autocomplete loads
#for file in ${(M)config_files:#*/completion.sh}
for file in $(find $ZSH/ -maxdepth 2 -name completion.sh)
do
  source $file
 done


# Better history
# Credits to https://coderwall.com/p/jpj_6q/zsh-better-history-searching-with-arrow-keys
#autoload -U up-line-or-beginning-search
#autoload -U down-line-or-beginning-search
#zle -N up-line-or-beginning-search
#zle -N down-line-or-beginning-search
#bindkey "^[[A" up-line-or-beginning-search # Up
#bindkey "^[[B" down-line-or-beginning-search # Down

if [ "$TERM" = "linux" ]; then
    echo -en "\e]P0222222" #black
    echo -en "\e]P8222222" #darkgrey
    echo -en "\e]P1803232" #darkred
    echo -en "\e]P9982b2b" #red
    echo -en "\e]P25b762f" #darkgreen
    echo -en "\e]PA89b83f" #green
    echo -en "\e]P3aa9943" #brown
    echo -en "\e]PBefef60" #yellow
    echo -en "\e]P4324c80" #darkblue
    echo -en "\e]PC2b4f98" #blue
    echo -en "\e]P5706c9a" #darkmagenta
    echo -en "\e]PD826ab1" #magenta
    echo -en "\e]P692b19e" #darkcyan
    echo -en "\e]PEa1cdcd" #cyan
    echo -en "\e]P7ffffff" #lightgrey
    echo -en "\e]PFdedede" #white
    clear #for background artifacting
fi





# start tmux by default
# https://www.reddit.com/r/tmux/comments/5nj8yi/am_i_nesting_session/
if [ "$TMUX" == "" ] ; then
    tmux attach || tmux new -s base
fi



